name: Notify PR

on:
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    notify-pr:
        name: "Notify PR"
        runs-on: ubuntu-latest

        steps:
          - uses: BakeFoundry/bk-bake-pr-reviewes@v1
            with:
              discord_webhook: ${{secrets.BK_DISCORD_WEBHOOK}}
